# Use a Node.js 18 base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Set environment variables
ENV DB_HOST /run/secrets/db_host
ENV JWT_SECRET /run/secrets/jwt_secret

# Expose the port the app runs on
EXPOSE 5000

# Command to run the app
CMD ["npm", "start"]
